[package]
name = "ohdlc"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.3.0", features = ["auto-color"] }
bumpalo = { version = "3.14.0", features = ["collections"] }
lasso = "0.7.2"
logos = "0.13.0"
once_cell = "1.19.0"
